money/money/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(pattern_name='payments')),
    url(r'payments/', include('payments.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

money/payments/urls.py
from django.conf.urls import url

from . import views
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='payments')),

    url('^view/all/$', views.payments, name='payments'),
    url('^view/my/$', views.my_payments, name='my_payments'),

    url('^deal/([0-9]+)/$', views.deal_payment, name='deal_payment'),
]

money/payments/models/payments.py
# *-- coding: utf-8 -*-
import datetime

from django.db import models
from django.contrib.auth.models import User

from taggit.managers import TaggableManager
from taggit.models import TaggedItemBase

from .stores import Store


class TaggedContents(TaggedItemBase):
    content_object = models.ForeignKey('Payment')


class Payment(models.Model):
    """
    Payment class
    """

    user = models.ForeignKey(User, verbose_name=u"Плательщик")
    amount = models.FloatField(verbose_name=u"Сумма")
    date = models.DateTimeField(verbose_name=u"Время", default=datetime.datetime.now)
    place = models.ForeignKey(Store, verbose_name=u"Место")
    contents = TaggableManager(through=TaggedContents)

    payers = models.ManyToManyField(User, through='PaymentDealingQuota',
                                    related_name='payed_payments')

    @property
    def dealed(self):
        return self.payers.exists()


class PaymentDealingQuota(models.Model):
    """
    Payment dealing quota class: describes amount of money that each user have to pay as a part of this payment
    """

    user = models.ForeignKey(User)
    payment = models.ForeignKey(Payment)
    amount = models.FloatField(verbose_name=u"Сумма")

money/payments/models/stores.py
# *-- coding: utf-8 -*-
from django.db import models


class StoreType(models.Model):
    """
    Store type: restaurant, food store, etc
    """
    name = models.CharField(verbose_name=u"Название", max_length=255)

    def __unicode__(self):
        return self.name


class Store(models.Model):
    """
    Store class: describes stores, restaurants and other places for spending money
    """
    name = models.CharField(verbose_name=u"Название", max_length=255)
    type = models.ForeignKey(StoreType, verbose_name=u"Тип")

    def __unicode__(self):
        return u"[{0}] {1}".format(self.type, self.name)

money/payments/views.py
from itertools import izip
from datetime import datetime, timedelta

from annoying.decorators import render_to
from django.contrib.auth.models import User
from django.db import transaction

from models.payments import Payment
from payments.models.stores import StoreType, Store
from payments.models import PaymentDealingQuota


@render_to('payments.html')
def payments(request):
    from_date = datetime.now() - timedelta(days=30)

    return {
        'from_date': from_date,
        'payments': Payment.objects
            .filter(date__gte=from_date)
            .order_by('-date')
    }

@render_to('my_payments.html')
def my_payments(request):
    if request.method == 'POST':
        store_type, created = StoreType.objects.get_or_create(name=request.POST.get('store_type'))

        store, created = Store.objects.get_or_create(name=request.POST.get('store_name'), type=store_type)

        amount = float(
            request.POST.get('amount', '0')
            .replace(',', '.')
            .replace(' ', '')
        )

        date = datetime.now()

        contents = request.POST.getlist('contents')

        payment = Payment(user=request.user, amount=amount, date=date, place=store)
        payment.save()
        payment.contents.add(*contents)

    from_date = datetime.now() - timedelta(days=30)

    return {
        'names_suggestlist': set(Store.objects.values_list('name', flat=True)),
        'store_types': StoreType.objects.all(),
        'from_date': from_date,
        'payments': Payment.objects
            .filter(date__gte=from_date, user=request.user)
            .order_by('-date')
    }

@render_to('deal_payment.html')
def deal_payment(request, payment_id):
    payment = Payment.objects.get(id=payment_id)

    if request.method == 'POST':
        with transaction.atomic():
            for user_id, amount in izip(
                    request.POST.getlist('user_id[]'),
                    request.POST.getlist('amount[]')):
                PaymentDealingQuota(
                    user_id=user_id,
                    payment=payment,
                    amount=amount
                ).save()

    return {
        'payment': payment,
        'users': User.objects.all()
    }

money/payments/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% if title %}{{ title }}{% else %}Бухгалтерия{% endif %}</title>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
        <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
        <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>

        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

        <!--[if lt IE 9]>
          <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <link rel="stylesheet" href="{% static "css/base.css" %}">

        {% block css %}{% endblock %}
        {% block js %}{% endblock %}
    </head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
        {% include "parts/navbar.html" %}
        </div>
    </div>

    <div class="container contents">
        <div class="header">
            {% block header %}{% endblock %}
        </div>

        {% block body %}{% endblock %}
    </div>
</body>
</html>

money/payments/templates/deal_payment.html
{% extends "base.html" %}
{% load static %}
{% load number_formatting %}

{% block js %}
    {{ block.super }}

    <script>
        var total = {{ payment.amount }};

        var controls = [];

        function abs_to_percents(abs_value) {
            return abs_value * 100 / total;
        }

        function percents_to_abs(percent_value) {
            return percent_value * total / 100;
        }

        function update(user_id, value) {
            // fit value into [0..100]
            value = Math.max(0, value);
            value = Math.min(100, value);

            // update all controls
            controls[user_id].slider.slider('value', value);
            controls[user_id].value.val(percents_to_abs(value));
            controls[user_id].percentage.val(value);

            // update equation
            var slider_sum = 0;
            $(".dealing_slider").each(function(index, value) {
                slider_sum += percents_to_abs($(value).slider("option", "value"));
            });
            $("#slider_sum").text(slider_sum);
            if(slider_sum == total) {
                $("#correct_equation").show();
                $("#incorrect_equation").hide();
                $("#submit_button").prop('disabled', false);
            } else {
                $("#incorrect_equation").show();
                $("#correct_equation").hide();
                $("#submit_button").prop('disabled', true);
            }
        }

        $(document).ready(function() {
            // BEGIN init controls array
            $(".dealing_slider").each(function(index, value){
                var user_id = $(this).data("userId");

                controls[user_id] = {};

                controls[user_id].slider = $(this);
            });

            $(".dealing_value").each(function(index, value){
                var user_id = $(this).data("userId");

                controls[user_id].value = $(this);
            });

            $(".dealing_percentage").each(function(index, value){
                var user_id = $(this).data("userId");

                controls[user_id].percentage = $(this);
            });
            // END init controls array


            $(".dealing_slider").slider({
                // TODO support mouse scroll on slider
                orientation: "vertical",
                range: "min",
                min: 0,
                max: 100,
                slide: function( event, ui ) {
                    update($(event.target).data("userId"), ui.value);
                }
            });

            $(".dealing_value").change(function() {
                var value = parseFloat($(this).val().replace(",", "."));

                update($(this).data("userId"), abs_to_percents(value));
            });

            $(".dealing_percentage").change(function() {
                var value = parseFloat($(this).val().replace(",", "."));

                update($(this).data("userId"), value);
            });

            // init values
            {% if payment.dealed %}
                {% for quota in payment.paymentdealingquota_set.all %}
                    update({{ quota.user_id }}, abs_to_percents({{ quota.amount }}));
                {% endfor %}
            {% else %}
                var initial_value = 100.0 / $(".dealing_slider").length;

                $(".dealing_slider").each(function() {
                    update($(this).data("userId"), initial_value);
                });
            {% endif %}
        });
    </script>
{% endblock %}

{% block css %}
    {{ block.super }}

    <style>
        .dealing_slider {
            width: 100%;
            height: 200px;
            border-radius: 0px;
        }

        .dealing_slider .ui-slider-handle {
            display: none;
        }

        .dealing_slider .ui-slider-range {
            border-radius: 0px;
        }

        .dealing_slider .ui-widget-header {
            background: #d9edf7;
        }

        #dealing {
            table-layout: fixed;
        }

        #dealing th, #dealing td {
            border-top: none;
        }

        #correct_equation {
            color: #3c763d;
            margin-top: 10px;
        }

        #incorrect_equation {
            color: #a94442;
            margin-top: 10px;
        }
    </style>
{% endblock %}


{% block header %}
    {{ block.super }}

    <div class="starter-template">
        <h1>
            {{ payment.amount | currency:"{0}&#8381;" }} в <a href="#">{{ payment.place }}</a>
        </h1>
        <p class="lead">
            Заплатил {{ payment.user }} в {{ payment.date }}
        </p>
    </div>
{% endblock %}


{% block body %}
    <form method="POST">
        {% csrf_token %}
        <table id="dealing" class="table">
            <tr>
                {% for user in users %}
                    <th>{{ user }}</th>
                {% endfor %}
            </tr>
            <tr>
                {% for user in users %}
                    <td>
                        <div class="dealing_slider" data-user-id="{{ user.id }}"></div>
                    </td>
                {% endfor %}
            </tr>
            <tr>
                {% for user in users %}
                    <td>
                        <input type="hidden" name="user_id[]" value="{{ user.id }}">

                        <p>
                            <div class="input-group">
                                <input type="text" name="amount[]" class="form-control dealing_value" data-user-id="{{ user.id }}">
                                <span class="input-group-addon">&#8381;</span>
                            </div>
                        </p>

                        <p>
                            <div class="input-group">
                                <input type="text" class="form-control dealing_percentage" data-user-id="{{ user.id }}">
                                <span class="input-group-addon">%</span>
                            </div>
                        </p>
                    </td>
                {% endfor %}
            </tr>
        </table>

        <div class="row">
            <div class="col-md-4">
                <button id="submit_button" type="submit" class="btn btn-success btn-lg">Сохранить</button>
            </div>
            <div class="col-md-8">
                <h2 id="correct_equation">
                    &Sigma; = {{ payment.amount }}
                </h2>
                <h2 id="incorrect_equation" style="display: none;">
                    &Sigma; = <span id="slider_sum">0</span> &ne; {{ payment.amount }}
                </h2>
            </div>
        </div>
    </form>
{% endblock %}

money/payments/templates/my_payments.html
{% extends "base.html" %}
{% load static %}

{% block header %}
    {{ block.super }}

    <div class="starter-template">
        <h1>Мои платежи</h1>
        <p class="lead">История моих платежей за последний месяц</p>
    </div>
{% endblock %}

{% block css %}
    {{ block.super }}

    <link rel="stylesheet" href="{% static "css/bootstrap-tagsinput.css" %}">
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static "js/bootstrap-tagsinput.min.js" %}"></script>
    <script src="{% static "js/bootstrap3-typeahead.min.js" %}"></script>
    <script>
        {{ block.super }}
        $(document).ready(function(){
            $("#store_type-choices a").click(function() {
                $("#store_type").val($(this).text());
            });

            var names = ['{{ names_suggestlist|join:"', '" }}'];

            $("#store_name").typeahead({ source:names });
        });
    </script>
{% endblock %}

{% block body %}
    <div id="new-entry" class="panel panel-default">
        <a data-toggle="collapse" href="#new-entry-form">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-plus"></span> Добавить
            </div>
        </a>
        <div id="new-entry-form" class="panel-collapse collapse">
            <div class="panel-body">
                <form class="form-horizontal" method="POST" role="form">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                          <label class="col-md-4 control-label" for="store_type">Тип</label>
                          <div class="col-md-4">
                            <div class="input-group">
                              <input id="store_type" name="store_type" class="form-control" placeholder="---" type="text" required="">
                              <div class="input-group-btn">
                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                  Выбрать
                                  <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu pull-right" id="store_type-choices">
                                  {% for store_type in store_types %}
                                    <li><a href="#">{{ store_type.name }}</a></li>
                                  {% endfor %}
                                </ul>
                              </div>
                            </div>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-md-4 control-label" for="store_name">Название</label>
                          <div class="col-md-4">
                              <input id="store_name" name="store_name" type="text" placeholder="---" autocomplete="off" class="form-control input-md" required="">
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-md-4 control-label" for="amount">Сумма</label>
                          <div class="col-md-4">
                              <input id="amount" name="amount" type="text" placeholder="00.00" class="form-control input-md" required="">
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-md-4 control-label" for="contents">Покупки</label>
                          <div class="col-md-4">
                              <select id="contents" name="contents" multiple data-role="tagsinput"></select>
                          </div>
                        </div>

                        <div class="form-group">
                          <label class="col-md-4 control-label" for="submit"></label>
                          <div class="col-md-4">
                              <button id="submit" name="submit" type="submit" class="btn btn-default">Сохранить</button>
                          </div>
                        </div>

                    </fieldset>
                </form>
            </div>
        </div>
    </div>

    {% with payments=payments %}
        {% include "parts/payments_table.html" %}
    {% endwith %}
{% endblock %}

money/payments/templates/parts/navbar.html
<div class="navbar-header">
    <a class="navbar-brand" href="/">Бухгалтерия</a>
</div>
<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Платежи <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="{% url "my_payments" %}">Мои платежи</a></li>
            <li><a href="{% url "payments" %}">Все платежи</a></li>
            <li class="divider"></li>
            <li><a href="#">Графики</a></li>
          </ul>
        </li>
        <li><a href="#">Распределение долгов</a></li>
        <li><a href="#">Статистика</a></li>
    </ul>
</div>

money/payments/templates/parts/payments_table.html
{% load number_formatting %}

<table class="table table-striped">
    <tr>
        <th>Где</th>
        <th>Что</th>
        <th>Сумма</th>
        <th>Кто</th>
        <th>Когда</th>
        <th>Распределение</th>
    </tr>
    {% for payment in payments %}
        <tr>
            <td>{{ payment.place }}</td>
            <td>
                <ul>
                    {% for entry in payment.contents.names %}
                        <li>{{ entry }}</li>
                    {% endfor %}
                </ul>
            </td>
            <td>{{ payment.amount | currency }}</td>
            <td>{{ payment.user }}</td>
            <td>{{ payment.date|date:"SHORT_DATETIME_FORMAT" }}</td>
            <td>
                <a href="{% url "deal_payment" payment.id %}"
                    {% if payment.dealed %}
                        style="color: green;"
                    {% endif %}
                >
                    {% if payment.dealed %}
                        <span class="glyphicon glyphicon-ok-sign"></span>
                    {% else %}
                        <span class="glyphicon glyphicon-question-sign"></span>
                    {% endif %}
                </a>
            </td>
        </tr>
    {% endfor %}
</table>

money/payments/templates/payments.html
{% extends "base.html" %}

{% block header %}
    {{ block.super }}

    <div class="starter-template">
        <h1>Платежи</h1>
        <p class="lead">История всех платежей c {{ from_date|date:"SHORT_DATE_FORMAT" }}</p>
    </div>
{% endblock %}

{% block body %}
    {% with payments=payments %}
        {% include "parts/payments_table.html" %}
    {% endwith %}
{% endblock %}